---
- name: Q13 - Playbook to manage webcontent
  hosts: dev
  gather_facts: true
  become: true
  tasks:
    - name: task1-creating webdev group
      ansible.builtin.group:
        name: webdev
        state: present

    - name: task2-installing required packages if missing
      ansible.builtin.dnf:
        name: [httpd,firewalld]
        state: present

    - name: task3-starting and enabling services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: task4-allowing http service over firewall
      ansible.posix.firewalld:
       service: http
       state: enabled
       permanent: true
       immediate: true
       offline: true

    - name: task4-creating /webdev directory
      ansible.builtin.file:
        state: directory
        path: /webdev
        owner: apache
        group: webdev
        mode: '2775'
        setype: httpd_sys_content_t

    - name: task5-creating index.html 
      ansible.builtin.copy:
        content: Development
        dest: /webdev/index.html
        mode: '0644'
        owner: apache
        setype: httpd_sys_content_t

    - name: task6-creating symbolic link
      ansible.builtin.file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        setype: httpd_sys_content_t

