---
- name: Q17 - Playbook to configure cron
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: task1-create student if not exists
      ansible.builtin.user:
         name: student
         state: present

    - name: task2-configuring cron
      ansible.builtin.cron:
        user: student
        name: ex294_cron
        job: logger "EX294 in progress"
        minute: "*/2" 
