---
- name: Q19 - Playbook to configure SELinux
  hosts: all
  gather_facts: true
  become: true
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
  tasks:
    - name: Configuring SELinux
      ansible.builtin.import_role:
        name: rhel-system-roles.selinux
