---
- name: Q2 - Playbook to configure repositories
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: task-1 importing rpm-gpg key
      ansible.builtin.rpm_key:
        key: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
        state: present

    - name: task-2 configuring base repo
      ansible.builtin.yum_repository:
        file: ex294
        state: present
        name: EX294_BASE
        description: EX294 base software
        baseurl: http://10.10.1.200/alma10/BaseOS
        enabled: true
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
         

    - name: task-2 configuring app-stream repo
      ansible.builtin.yum_repository:
        file: ex294
        state: present
        name: EX294_STREAM
        description: EX294 stream software
        baseurl: http://10.10.1.200/alma10/AppStream
        enabled: true
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
         
