---
- name: Playbook-1 Install php-mariadb
  hosts: dev,test,prod
  gather_facts: false
  become: true
  tasks:
    - name: Install php-mariadb
      ansible.builtin.dnf:
        name: [php,mariadb]
        state: present

- name: Playbook-2 Install rpm-dev-tools and upgrade
  hosts: dev
  gather_facts: false
  become: true
  tasks:
    - name: Install RPM Dev Tools
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present


    - name: upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
