---
- name: Q7 - Playbook to manage /etc/issue file
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: play-1 configuring /etc/issue file
      ansible.builtin.copy:
        content: |
          {% if 'dev' in group_names %}
          Development
          {% elif 'test' in group_names %}
          Test
          {% elif 'prod' in group_names %}
          Production
          {% endif %}
        dest: /etc/issue
        owner: root
        group: root
        mode: '0644'
